### ISSUE TITLE
No way to modify input size

### ISSUE THREAD

**Issue by btaens** [Holt59/cakephp3-bootstrap3-helpers#13]
Hey,
Really nice plugin here, but I can't seem to find any way to change input size (input-lg, input-sm, input-xs). If I provide a "class" option to Form->input, it simply ignores it.

**Comment by Holt59** [comment]
Latest commit should fix it.

**Comment by btaens** [comment]
Works like a charm! Thank you! Make sure to update the composer reference, so composer pulls the newest version.

**Comment by btaens** [comment]
Oh, sorry, I'm dumb, my composer just had it cached.

**Comment by Holt59** [comment]
I updated packagist this morning after your comment, meaning it probably wasn't working before.
