### ISSUE TITLE
Ajax load Porblem

### ISSUE THREAD

**Issue by stefanodalpos** [Holt59/cakephp3-bootstrap3-helpers#14]
I'm developing a small backend with your Helpers, but when i try to get some content via ajax the inputs get original Cake php Form structure
```html
<div class="input text"><label for="images-0-description">Description</label><input type="text" name="images[0][description]" id="images-0-description"></div>
```
instead of
```html
<div class="form-group text"><label class=" control-label" for="images-0-description">Description</label><input class="form-control" type="text" name="images[0][description]" id="images-0-description"></div>
```
thats normally loaded

**Comment by Holt59** [comment]
I don't think this is a plugin related issue, maybe you're not loading the plugin or setting the helpers correctly when you receive a ajax request.

**Comment by stefanodalpos** [comment]
i load the plugin application wide in AppController, the only thing that is different from edit.ctp (normal load) and the image-list.ctp used for ajax, is that i don't use
```php
$this->Form->create()
```
but probably can be a Cakephp3 bug

**Comment by Holt59** [comment]
In this case it's plugin related but it has nothing to do with ajax call. I will update the plugin with a more clean version which should fix this issue, but I don't know when (probably not before a month or two... ). 

Currently, the easiest way to deal with it is to call `$this->Form->create()` without printing it.

**Comment by stefanodalpos** [comment]
esactly what i try a moment ago... and it works!
Thanks! goodJob!
