### ISSUE TITLE
Help text option to inputs

### ISSUE THREAD

**Issue by danielfpedro** [Holt59/cakephp3-bootstrap3-helpers#17]
Type: Feat. request

The same awesome job that you did putting `append` and `prepend` options I think you could put a `help text` option that insert after the input a text, something like that:

    $this->Form->input('name', ['helpText' => 'bla bla bla');
    //Html generated
    //<input ...><p class="help-block">bla bla bla</p>

**Comment by Holt59** [comment]
Again, check the latest commit ;) I use `help` instead of `helpText`, so simply use:
```php
echo $this->Form->input('pseudo', ['help' => 'Give me your name!']);
```
Update works with error but the help text will be red colored (as it is with bootstrap), I can't change that.

Hope it'll help!

**Comment by danielfpedro** [comment]
Aew
