### ISSUE TITLE
Input file issue

### ISSUE THREAD

**Issue by danielfpedro** [Holt59/cakephp3-bootstrap3-helpers#18]
On form template:

    <?= $this->Form->file('imagem_capa') ?>

Is raising this error:

    Undefined index: id [ROOT\vendor\holt59\cakephp3-bootstrap3-helpers\src\View\Helper\BootstrapFormHelper.php, line 421]

**Comment by danielfpedro** [comment]
I'm using cakephp 3.0.1 and the lastest version of your plugin

**Comment by Holt59** [comment]
Should be working now, but with old input file. If you want to try the new one, add the following when enabling the helper:
```php
public $helpers = [
    'Form' => [
        'className' => 'Bootstrap3.BootstrapForm',
        'useCustomFileInput' => true
    ],
];
```
See the upcoming documentation at https://holt59.github.io/cakephp3-bootstrap3-helpers/.

**Comment by danielfpedro** [comment]
Sorry about my ignorance but what you mean "old input file" ?

**Comment by Holt59** [comment]
A few commits ago, I created a new file input which is not standard with bootstrap (actually, there is no bootstrap file input, just the standard one). If you want to try it, use the code I specified above or check the documentation (search for « file input »). 

Whatever file input you use (default or customize), you should not get anymore error.

Hope you like the new file inputs!
