### ISSUE TITLE
Input file issue with error and help option

### ISSUE THREAD

**Issue by danielfpedro** [Holt59/cakephp3-bootstrap3-helpers#19]
The file input is not working the options "help" and the validation errors

**Comment by Holt59** [comment]
Working fine here, with both type of file inputs. Show me your code.

**Comment by danielfpedro** [comment]
<?= $this->Form->create($event, ['type' => 'file', 'horizontal' => true, 'novalidate' => true]); ?>
    <?= $this->Form->file('imagem_capa_placeholder', ['help' => 'A imagem deve conter no máximo 1MB.']) ?>
    ...

HTML generated:

    <input type="file" name="imagem_capa_placeholder" help="A imagem deve conter no máximo 1MB." required="required">

HTML Generator on validation error:

    <input type="file" name="imagem_capa_placeholder" help="A imagem deve conter no máximo 1MB." class="has-error" required="required">

**Comment by danielfpedro** [comment]
I think the input file is not being wrapped by `form-group`. I need to do this manually?

**Comment by Holt59** [comment]
If you use raw method (`file`, `text`, `checkbox`, etc.), most of the options won't work and you will not get any errors or label output (as with default CakePHP). If you want to have `label`, `error` or `help` message, you need to use `input` method:
```php
<?= $this->Form->create($event, ['type' => 'file', 'horizontal' => true, 'novalidate' => true]); ?>
<?= $this->Form->input('imagem_capa_placeholder', ['type' => 'file', 'help' => 'A imagem deve conter no máximo 1MB.']) ?>
```

**Comment by danielfpedro** [comment]
ye, I tried now this now and worked, thanks.
