### ISSUE TITLE
Bootstrap style button for file browsing?

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#20]
Hi Mickaël,

Did I miss something or you forgot to patch the input file button like http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/ ? ;-)

Regards,
Alain

**Comment by Holt59** [comment]
There is a custom file input you can use by setting `useCustomFileInput` to `true` when loading the helper:
```php
public $helpers = [
    'Form' => [
        'className' => 'Bootstrap3.BootstrapForm',
        'useCustomFileInput' => true
    ],
] ;
```
This my own custom file input, if you want to use the one described in your link, feel free to open a pull request !

**Comment by caBBAlainB** [comment]
Ok, thanks, I try it.

**Comment by caBBAlainB** [comment]
Is there a specific label for the button?

**Comment by Holt59** [comment]
I added an option `button-label` in commit 5c6dea0edd06d0a869e50ab16829e8e4a14c5d0d
