### ISSUE TITLE
New feature for custom input file

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#21]
Hi,
One thing I find really stupid about input file is to not be able to clear the selected file.
So we can find many various solutions but one which seems to be the best is that very simple one http://jsfiddle.net/Xotic750/pfeBs/
And despite some comments, it perfectly works on IE11, don't know on previous version and FF and Chrome.

So, as 'useCustomFileInput_2' => true maybe, would it be possible to have a file input with a button which toggles between 'Browse' (or better, the given label) and 'Delete' with color 'danger' (or better, another given label)?

Regards,
Alain

**Comment by Holt59** [comment]
I cannot add everything in the standard helpers. I will try to add a sort of "plugin" option in the helpers in a future update to allow anyone to choose what he wants to use.

**Comment by caBBAlainB** [comment]
Ok, maybe a good idea.
