### ISSUE TITLE
Just for info: bootstrap like checkboxes and radios

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#22]
I suppose you already know this .. https://github.com/flatlogic/awesome-bootstrap-checkbox

**Comment by caBBAlainB** [comment]
There is a little problem with this checkboxes you may fix I think.

You currently layout the label/input as below::

    <div class="checkbox">
        <input type="hidden" name="preload" class="form-control "  value="0" />
        <label for="preload"><input type="checkbox" name="preload" value="1" id="preload" checked="checked">Préchargement du point d&#039;intérêt</label>
    </div>

And according to the doc here https://github.com/flatlogic/awesome-bootstrap-checkbox#use, that cause the checkbox to not working.

So the correct layout should be as follow, notice the start <label> tag put after <input>. That won't change anything visualy or functionnaly I think::
									
    <div class="checkbox">
        <input type="hidden" name="preload" class="form-control "  value="0" />
        <input type="checkbox" name="preload" value="1" id="preload" checked="checked">
        <label for="preload">Préchargement du point d&#039;intérêt</label>
    </div>

**Comment by Holt59** [comment]
Hi Alain, the helpers are made to work with default bootstrap, the plugin you linked is not using the default bootstrap markup (see http://getbootstrap.com/css/#forms).

**Comment by caBBAlainB** [comment]
Ok Mickael but as shows the first code block which, if I didn't mistaken is the layout you provide, you don't respect the rule http://getbootstrap.com/css/#don%27t-mix-form-groups-with-input-groups
input should be outside the label, as also specify the link I gave you about the new checkbox shape no?

**Comment by Holt59** [comment]
Check the link I provided (http://getbootstrap.com/css/#forms), and you'll see that `checkbox` and `radio` inputs are inside the label:
```html
<div class="checkbox">
  <label>
    <input type="checkbox"> Check me out
  </label>
</div>
```
The only thing that change between the bootstrap example and my code is the `hidden` input which has no effect on the global output.

**Comment by caBBAlainB** [comment]
Ah! for checkboxes ok, which is strange as all others are not made in the same way !?!
I didn't found an explanation about that choice.
