### ISSUE TITLE
Submit buttons use class .btn-default and can't be changed...

### ISSUE THREAD

**Issue by lyz452** [Holt59/cakephp3-bootstrap3-helpers#23]
It tried to add class .btn-primary but .btn-default stays in there and wins over it. 
I also tried passing an option ['type' => 'primary'] like you do with the alerts in your example but it's no good too.

**Comment by Holt59** [comment]
The option name is `bootstrap-type`, which only works for standard types as defined here:
```php
private $buttonTypes = ['default', 'primary', 'info', 'success', 'warning', 'danger', 'link'] ;
```
If you want to use a custom type, set `bootstrap-type` to false.

**Comment by lyz452** [comment]
Thank you
