### ISSUE TITLE
Option 'prepend' also automatically add an addon at the end of the field (option 'append')

### ISSUE THREAD

**Issue by lyz452** [Holt59/cakephp3-bootstrap3-helpers#24]
Example:
![form-bug](https://cloud.githubusercontent.com/assets/8060092/7818809/eb9080cc-03ab-11e5-9b20-01b6de77efb1.png)

**Comment by Holt59** [comment]
Should be correct with commit 5fd8d6ca215e465c7b2fde0b14ffea1c4c3c48ad.

**Comment by lyz452** [comment]
Thank you!
