### ISSUE TITLE
Form template example

### ISSUE THREAD

**Issue by AntoineIM** [Holt59/cakephp3-bootstrap3-helpers#28]
Hello,
I'm pretty new with CakePHP. Do you have an example how to use form element template with your helper? In my specific case, in my form, there is a birth date to fill, and I would like to use this template:
```php
'dateWidget' => '{{day}}{{month}}{{year}}'
```
instead of 
```php
'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}'
```

Thanks for your help.

**Comment by Holt59** [comment]
Hi,

With the latest update, you should be able to do what you want by specifying the template when creating the input:
```php
echo $this->Form->input(NULL, [
    'type' => 'date', 
    'templates' => [
        'dateWidget' => '{{day}}{{month}}{{year}}'
    ]
]) ;
```

If you want to use it in all your date input, you can specify the templates when loading the helper:
```php
public $helpers = [
    'Form' => [
        'className' => 'Bootstrap3.BootstrapFormHelper',
        'templates' => [
            'dateWidget' => '{{day}}{{month}}{{year}}{{hour}}{{minute}}{{second}}{{meridian}}'
        ]
    ]
] ;
```

**Comment by AntoineIM** [comment]
Hello @Holt59 
Great, thank you for this improvement!
Bonne journée ;)
