### ISSUE TITLE
Wrapping Div Un-Editable...

### ISSUE THREAD

**Issue by lyz452** [Holt59/cakephp3-bootstrap3-helpers#29]
In Cake2, I could use the 'div' options to edit the wrapping div (add classes or an ID or whatever else) but right now the .form-group div is hard-coded... I don't know how to make that edit myself...

**Comment by Holt59** [comment]
In CakePHP3 (not only my helpers), you cannot access the wrapping `div` element, you can only override the whole `div` template.

**Comment by Holt59** [comment]
Actually, if you want you can specify a new template when calling `BootstrapFormHelper::create` or `BootstrapFormHelper::input`:
```php
echo $this->Form->create(null, [
    'templates' => [
        'inputContainer' => '<div class="form-group my-class {{type}}{{required}}">{{content}}</div>'
    ]
]);
```
