### ISSUE TITLE
Companies using CakePHP

### ISSUE THREAD

**Issue by bobmulder** [Holt59/cakephp3-bootstrap3-helpers#32]
Hey @Holt59,

Thanks for the nice plugin. We are using it for the [CakeAdmin](https://github.com/cakemanager/cakephp-cakeadmin) Plugin (https://github.com/cakemanager/cakeadmin-lightstrap).
Maybe you should think about a 'Companies using CakePHP' section? ;)

Greetz

Bob

**Comment by barberemi** [comment]
Thanks @Holt59 for this plugin :)
It works very well.

But i have a question : can you do a postLink ($this->Form->postLink) with confirmation of suppression?

Thx 
Rémi

**Comment by Holt59** [comment]
Hi @barberemi,

If what you are looking are bootstrap-like confirm dialog windows, then it cannot be done without simple javascript (you'll need an extra bootstrap plugin such as [bootbox](http://bootboxjs.com/)).

If this is not what you are looking for, please open a new issue with a bit more of details !

Thanks,

Mikael
