### ISSUE TITLE
Checkbox issue in basic form example

### ISSUE THREAD

**Issue by GLacourt** [Holt59/cakephp3-bootstrap3-helpers#33]
Thanks for those helpers it's saving a lot of time for our dev team.

However we have an issue with basic form and checkbox input. The helper add a .form-group div element which wrap .checkbox div element.

It break some advanced form building and we have to had manually a new template string for this case.

It should be awesome if your helper can improve this feature and dynamicaly add the wrapping form-group depending on the case of utilisation.

**Comment by Holt59** [comment]
Should be fixed by commit ce0653d39721c23c780108c50ce064d795b53390. Let me know if it does not work!
