### ISSUE TITLE
Composer require fail

### ISSUE THREAD

**Issue by bobmulder** [Holt59/cakephp3-bootstrap3-helpers#34]
Hey,

First of all thanks for the nice plugin. We are using it for https://github.com/cakemanager/cakeadmin-lightstrap.
I am trying to get composer working but get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakemanager/cakeadmin-lightstrap dev-master -> satisfiable by cakemanager/cakeadmin-lightstrap[dev-master].
    - cakemanager/cakeadmin-lightstrap dev-master requires holt59/cakephp3-bootstrap3-helpers dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

So can you tell me why composer sais that your package couldn't be found?

Thanks!

**Comment by Holt59** [comment]
Hi, can you show me your `composer` file?

**Comment by bobmulder** [comment]
Of course :) https://github.com/cakemanager/cakeadmin-lightstrap/blob/master/composer.json

**Comment by bobmulder** [comment]
@Holt59 Could you find something stupid?

**Comment by Holt59** [comment]
I don't see anything obvious but I am not a composer expert. I will try to have a closer look at it tomorrow if I can. 

Maybe you should ask the question to the composer community.

**Comment by Holt59** [comment]
I did not manage to reproduce your bug. I created a new project and installed your plugin running the following:
```shell
php composer.phar create-project --prefer-dist cakephp/app test_cakeadmin
cd test_cakeadmin
php ..\composer.phar require cakemanager/cakeadmin-lightstrap:dev-master
```
Output:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing holt59/cakephp3-bootstrap3-helpers (dev-master ce0653d)
    Cloning ce0653d39721c23c780108c50ce064d795b53390

  - Installing cakemanager/cakeadmin-lightstrap (dev-master 995a199)
    Cloning 995a199648649b62975e4394cc26995fe99cb239

Writing lock file
Generating autoload files
```

**Comment by bobmulder** [comment]
Hey @Holt59,

Thanks for your feedback. Have no idea whats going wrong then, but it should be our fault.. Sorry ;)

Again, thanks for the plugin :)

Greetz,

Bob
