### ISSUE TITLE
Infinite loop since 1f69396

### ISSUE THREAD

**Issue by btaens** [Holt59/cakephp3-bootstrap3-helpers#36]
Hello,

The helper seems to get stuck in an infinite loop since the latest patch:
15	0.0616	4201232	call_user_func_array ( )	../BootstrapFormHelper.php:220
16	0.0616	4201728	Bootstrap3\View\Helper\BootstrapFormHelper->date( )	../BootstrapFormHelper.php:220
17	0.0617	4203576	Bootstrap3\View\Helper\BootstrapFormHelper->_wrapTemplates( )	../BootstrapFormHelper.php:576
18	0.0617	4203352	call_user_func_array ( )	../BootstrapFormHelper.php:220
19	0.0617	4203776	Bootstrap3\View\Helper\BootstrapFormHelper->date( )	../BootstrapFormHelper.php:220
20	0.0618	4205624	Bootstrap3\View\Helper\BootstrapFormHelper->_wrapTemplates( )	../BootstrapFormHelper.php:576
21	0.0618	4206080	call_user_func_array ( )	../BootstrapFormHelper.php:220
22	0.0618	4206504	Bootstrap3\View\Helper\BootstrapFormHelper->date( )	../BootstrapFormHelper.php:220

...and so on, until either xdebug reaches its nesting level or execution time runs out.

**Comment by Holt59** [comment]
Hi,

Could you post the code which produce this infinite loop (your call to
date)?

**Comment by btaens** [comment]
Sure, though there's nothing special about it:
```php
echo $this->Form->input('birth_date');
```

birth_date is a date dataType. The only special thing I can think about is my form initiation:
```php
echo $this->Form->create(new \App\Model\Entity\User());
```
I basically pass a newly created user entity instead of an existing record.

**Comment by Holt59** [comment]
I am not able to reproduce your bug. I have created a `mysql` table with a `birth_date` field (type `date`), and with the following:
```php
echo $this->Form->create(new \App\Model\Entity\User());
echo $this->Form->input('birth_date') ;
echo $this->Form->end () ;
```
I get the expected output (3 selects).

How do you initialize the `Helper` in your `Controller`? Also check if you have the latest version of the plugin (maybe there were some delay because of composer... ).

**Comment by btaens** [comment]
Alright, did some debugging, and I think I have the problem.

BootstrapFormHelper::date() returns the following:
```php
return $this->_wrapTemplates ([
    'dateWidget' => $this->_getDatetimeTemplate($fields, $options)
], [$this, 'parent::date'], [$fieldName, $options]);
```
Now, it passes parent::date as a callback function, or in other words, FormHelper::date().

However, I have extended BootstrapFormHelper to MyFormHelper. This way, parent::date becomes BootstrapFormHelper::date, which calls _wrapTemplates(), which calls date(), and so on.

**Comment by btaens** [comment]
Instead of using [$this, 'parent::date'], it should be [__CLASS__, 'parent::date'], as $this will always be the top level class.

**Comment by Holt59** [comment]
Thanks for your debugging, I've done some checking and both `[__CLASS__, 'parent::date']` and `[$this, 'FormHelper::date']` work. I cannot update the repository right now, but I will do some digging since I am not familiar with the `__CLASS__` keyword and see which one of the two options is the proper way of doing this.

**Comment by Holt59** [comment]
Okay so apparently the best way is to simply use `parent::date` (without an array). I did an update, check it out!

**Comment by btaens** [comment]
Yup, that works. Thank you!
