### ISSUE TITLE
escape horizontal Form

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#37]
Hi,

When we use Form->create(...., ['horizontal' => true']), is it possible to ask a specific input to ignore 'horizontal' => true?
Just because that cause a problem with one of the plugin I use.

**Comment by Holt59** [comment]
Hi Alain, check commit a79747c1b2c8fecb8c4c141b53fd525175a6175f, I added a `setHorizontal` method (you should call it before your specific input with `false` and after with `true`).
