### ISSUE TITLE
Bake?

### ISSUE THREAD

**Issue by Oxicode** [Holt59/cakephp3-bootstrap3-helpers#38]
Hola

Seria muy util tener el comando el bake con el template

**Comment by Holt59** [comment]
Could you elaborate on what you would like the `bake` command to do?

**Comment by danielfpedro** [comment]
@Oxicode You just have to add the plugin and load it... All of your forms baked will get the template.

**Comment by Oxicode** [comment]
Miren esto:

https://github.com/FriendsOfCake/bootstrap-ui/tree/master/src/Template/Bake/Template

**Comment by Holt59** [comment]
@Oxicode The goal of this repository is only to provide helpers, not some kind of ready-to-go CakePHP/Bootstrap application. Every site has its own layout, so I'm not sure that providing a default layout would have any benefit.
