### ISSUE TITLE
NavbarHelper - Calling addClass with Array throws notice

### ISSUE THREAD

**Issue by raul338** [Holt59/cakephp3-bootstrap3-helpers#41]
The following code
```php
echo $this->Navbar->create(
    'The Project',
    [
        'responsive' => true,
        'fluid' => true,
        'fixed' => 'top'
    ]
);
echo $this->Navbar->beginMenu(['class' => 'navbar-right']);
    echo $this->Navbar->link(__('Exit'), ['controller' => 'Users', 'action' => 'logout']);
echo $this->Navbar->endMenu();
echo $this->Navbar->end();
```
throws the following notice
![screenshot_20150723_134210](https://cloud.githubusercontent.com/assets/7199046/8856366/b8fbf728-3140-11e5-8fed-b5d3ffd71aef.png)

if I change the beginMenu line in level 0:
```php
$options = $this->addClass ($options, ['nav', 'navbar-nav']);
```
to this
```php
$options = $this->addClass ($options, 'nav navbar-nav');
```
then it works

**Comment by raul338** [comment]
Another workaround would be changing the HtmlHelper
```php
'Html' => [
    'className' => 'Bootstrap3.BootstrapHtml'
]
```
and then change every `$this->addClass` with `$this->Html->addClass` (at least every one that uses array for classes)

**Comment by Holt59** [comment]
Ok, this should work now, I've made a copy of the `addClass` method inside the `BootstrapNavbarHelper`. I'll have to find a cleaner way since right now I have a copy of this method in each helpers...

**Comment by raul338** [comment]
Yep. Works fine by now

BTW: Packagist doesn't update sicen yesterday (I had to pull by hand)

**Comment by Holt59** [comment]
I forced the update on packagist, should be ok by now.
