### ISSUE TITLE
icon in breadcrumb

### ISSUE THREAD

**Issue by PeckySF** [Holt59/cakephp3-bootstrap3-helpers#45]
Hello,
I currently am using the helper in one of my projects, and I was wondering if it was possible to add the possiblity to use icons in the breadcrumbs ?
like this, by example : 
echo $this->Html->getCrumbList(null, $this->Html->icon('home'));

**Comment by Holt59** [comment]
Hi,
It's possible, you simply need to tell Cake not to escape HTML:
```php
echo $this->Html->getCrumbList(['escape' => false], $this->Html->icon('home')) ;
````
This is a standard CakePHP option.

**Comment by PeckySF** [comment]
Thanks
