### ISSUE TITLE
Problem with textarea

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#5]
Hello,

When I create a Form with textarea, it's the case of 'address', it doesn't fill the same horizontal space. 
How to do it?

<div class="col-md-10">
	<?= $this->Form->create($site, ['horizontal' => true]) ?>
		<fieldset>
			<?= $this->Form->input('name'); ?>
			<?= $this->Form->input('address', ['label' => __("Adresse du site :"), 'placeholder' => __("Adresse du site")]); ?>
		</fieldset>
		<?= $this->Form->button(__('Enregistrer')) ?>
	<?= $this->Form->end() ?>
</div>

**Comment by Holt59** [comment]
Hi, this should be fixed with the latest commit.

**Comment by caBBAlainB** [comment]
Perfect Holt59.
I was first a bit hesitating about such plugin but it really helps!

Is it possible to mix the fields layout? For example, in a Form, to have 2 fields side by side whereas all others are one above the other.

Thanks a lot.

**Comment by Holt59** [comment]
There is no built-in feature in the plugin to do what you want to do but you can simply use bootstrap grid like you will do without the plugin:

```
<?php
    echo $this->Form->create () ;
?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->Form->input('firstname') ; ?>
        </div>
        <div class="col-md-6">
            <?php echo $this->Form->input('lastname') ; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?php echo $this->Form->input('Mail') ; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?php echo $this->Form->input('Address') ; ?>
        </div>
    </div>

<?php
    echo $this->Form->end() ;    
?>
```

**Comment by caBBAlainB** [comment]
Ok, no problem
Thanks

**Comment by Holt59** [comment]
Hi Alain, I'm sorry don't really understand what you want...

Since the question is not related to the issue anymore, I close it, but feel free to send me a mail with more details about your needs.
