### ISSUE TITLE
id is defined twice

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#6]
Hello,
I saw that almost all input() excepting select and textarea; ie text, number, tel, etc... define the id twice:

`<div class="form-group tel required"><label class="col-md-2 control-label"  for="phone">Téléphone du site :</label><div class="col-md-6"><input class="form-control"  placeholder="Téléphone du site" required="required" maxlength="20" **id="phone"** type="tel" name="phone" **id="phone"** /></div></div>`

Do you confirm?

Alain

**Comment by Holt59** [comment]
Should be corrected with the latest commit. Thx for the feedback!

**Comment by caBBAlainB** [comment]
I'll check maybe tomorrow.
Thanks

**Comment by caBBAlainB** [comment]
The last commit is ok.
Thanks
