### ISSUE TITLE
`btn-default` is added even when `bootstrap-type` is set

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap3-helpers#7]
This code:
```php
<?= $this->Form->submit('Login', ['bootstrap-type' => 'primary']) ?>
```
Generates this HTML:
```html
<input type="submit" value="Login" class="btn btn-default btn-primary">
```

Note that there is `btn-primary` **and** `btn-default`. It don't causes any problems at the moment, but I'm pretty sure this is not allowed by Bootstrap.

**Comment by Holt59** [comment]
Latest commit should correct that. Thx for the feedback.
