### ISSUE TITLE
Small problem when not using composer

### ISSUE THREAD

**Issue by jmenges** [Holt59/cakephp3-bootstrap3-helpers#8]
If you simply clone the repository into plugins/Bootstrap3 it was necessary for me to use 
Plugin::load('Bootstrap3',  ['autoload' => true]);
instead of just
Plugin::load('Bootstrap3');
in config/bootstrap.php

Otherwise i get the following error:
![image](https://cloud.githubusercontent.com/assets/10944143/6130927/f0789954-b148-11e4-9a1b-e6a5badeec9e.png)

Maybe this should be added to the README.md

Cheers!

**Comment by Holt59** [comment]
Yes it should (and it is now ;)), thx for the feedback.
