### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap3-helpers#9]
Hi,
I would like to know if there is a way to display radio buttons one above the others.

Thks.

**Comment by Holt59** [comment]
Hi,

Radio buttons were not working before the latest commit (or if they were, it was pure luck... ). With the latest commit, the default behaviour is to have vertical radio buttons (like you want), to get horizontal ones you need to specify the `'inline' => true` option.

Unfortunately, there is a bug with horizontal forms and radio buttons **without label** which output something ugly. I don't have any clue on how to fix it right now but a simple way to get around is to specify an empty string as label instead of false:
```
$this->Form->create('MyModel', ['horizontal' => true]);
$this->Form->input('radio', ['type' => 'radio', 'options' => [...], 'label' => ' ']) ;
```

If you find any bugs, do not hesitate to create a new issue!

**Comment by caBBAlainB** [comment]
So I found how to get vertical buttons but when they are in a panel, they are displayed on the border. I don't know if it's because of the way I create it:

    			    <div class="panel panel-default">
    				   <div class="panel-heading">
    					  <h3><?= __("Nouvelle description du site {0}", $site->name); ?></h3>
    				   </div>
    				   <div class="panel-body">
                            <?= $this->FormB->create($order)?>
                                <?= $this->FormB->radio('description', $items,  ['label' => ["class" => "radio"]]); ?>
                                <br/>
                            </div>
                            <div>
                                <?= $this->Form->button(__("Enregistrer"), ["class" => "btn btn-primary btn-block"]) ?>
                            </div>
                        <?= $this->FormB->end() ?>
                    </div>

![2015-02-16 18_24_13-pros_sitemessages](https://cloud.githubusercontent.com/assets/9322571/6216322/51c2afe6-b609-11e4-89df-aaf8b2e94101.png)

**Comment by Holt59** [comment]
Hi Alain,

You should use the *input* method if you want bootsrap layout (i.e. d*i*v
with *form-group* class, etc.). In your case:

$this->FormB->radio('description', ['type' => 'radio', 'options' =>
$items, 'label' => ["class" => "radio"]]);


More details on this issue (this is another version of the helpers but it
should help you) :
https://github.com/Holt59/cakephp-bootstrap3-helpers/issues/8

Mikaël

Mikaël CAPELLE
5ème année, Informatique et Réseau
Institut National des Sciences Appliquées de Toulouse
+33 (0) 6 58 06 48 64
capelle.mikael@gmail.com

**Comment by Holt59** [comment]
Oops, little mistake in my answer:

$this->FormB->*input*('description', ['type' => 'radio', 'options' =>
$items, 'label' => ["class" => "radio"]]);


Mikaël


Mikaël CAPELLE
5ème année, Informatique et Réseau
Institut National des Sciences Appliquées de Toulouse
+33 (0) 6 58 06 48 64
capelle.mikael@gmail.com

**Comment by caBBAlainB** [comment]
In that case radios are inline. whereas I would prefer it one above the other.

**Comment by Holt59** [comment]
Do you use the latest version ? The one I pushed 30 minutes ago ? 

Commit : `6d7ea2ad9bcfd43b967acb3611a84c26f498486b`
